### ISSUE TITLE
Swapped keys (Backquote, IntlBackslash)

### ISSUE THREAD

**Issue by philippkuehn** [microsoft/node-native-keymap#15]
When using this library, `Backquote` and `IntlBackslash` keys are swapped. I can reproduce this with any keyboard layout. Am I doing something wrong?

### Layout

```js
{id: "com.apple.keylayout.German", localizedName: "German", lang: "de"}
```

### Keymap

```js
{
  // ...
  "Backquote": {
    "value": "<",
    "valueIsDeadKey": false,
    "withShift": ">",
    "withShiftIsDeadKey": false,
    "withAltGr": "≤",
    "withAltGrIsDeadKey": false,
    "withShiftAltGr": "≥",
    "withShiftAltGrIsDeadKey": false
  },
  "IntlBackslash": {
    "value": "^",
    "valueIsDeadKey": true,
    "withShift": "°",
    "withShiftIsDeadKey": false,
    "withAltGr": "„",
    "withAltGrIsDeadKey": false,
    "withShiftAltGr": "“",
    "withShiftAltGrIsDeadKey": false
  },
  // ...
}
```

### My System
native-keymap v2.1.0, macOS Catalina, node v12.12.0

**Comment by alexandrudima** [comment]
@philippkuehn Are you using Electron/Chromium by any chance? Have you tried logging the keyboard events in Safari?

Chromium, on ISO keyboards is swapping the keys here -- https://cs.chromium.org/chromium/src/ui/events/keycodes/keyboard_code_conversion_mac.mm?type=cs&q=LMGetKbdType+package:%5Echromium$&l=805-816.

```cpp
int ISOKeyboardKeyCodeMap(int nativeKeyCode) {
  // OS X will swap 'Backquote' and 'IntlBackslash' if it's an ISO keyboard.
  // https://crbug.com/600607
  switch (nativeKeyCode) {
    case kVK_ISO_Section:
      return kVK_ANSI_Grave;
    case kVK_ANSI_Grave:
      return kVK_ISO_Section;
    default:
      return nativeKeyCode;
  }
}
```

So this node module is honestly reporting what macOS is telling it, but Chromium swaps the keys **as the event comes in, but only if the event originated on an ISO keyboard**. Chromium motivates in that issue that it "fixes" macOS, because macOS is weird, and if the only source of observing the keyboard is through Chromium, their fix is fine. But this module goes directly to the OS...

The difficulty is that Chromium's swap is dynamic. A laptop for example can have a built-in ISO keyboard and an external ANSI keyboard. But Chromium will swap the codes only when pressing the backtick/intlbackslash on the ISO keyboard, so it is per keyboard event.

Here is how we have worked around it in VS Code:
1. [this was the initial workaround] We loaded up `native-keymap` in the main process. It must be loaded in the process that receives the keyboard events, because when a keyboard event comes in, macOS will tweak a certain global that indicates that the user is now typing at an ISO keyboard. Then, we would poll and call `isISOKeyboard()` - a method exposed by this module. Finally, we would send this information to the renderer process and implement the corresponding workarounds there...
2. [this is our current workaround] We have the luxury of building Chromium from sources. We have simply patched Chromium and removed the swap in Chromium.

You can see when we saw this issue here -- https://github.com/microsoft/vscode/issues/24153

**Comment by philippkuehn** [comment]
@alexandrudima thank you for this detailed explanation! And yes I'm using electron. I swapped these two keys and it's working great for now. Super great library!
